version: '3.10'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    shm_size: '6gb'
    environment:
      - PYTHONUNBUFFERED=1